# Generated by Django 5.2.17 on 2026-08-29 16:37

import apps.accounts.managers
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="adresse e-mail"
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "is_super_admin",
                    models.BooleanField(
                        default=False,
                        help_text="Rôle unique au sommet de la hiérarchie (1 à 2 comptes maximum).",
                        verbose_name="Super Administrateur",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invité"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("offboarded", "Parti"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("preferred_language", models.CharField(default="fr", max_length=5)),
                ("timezone", models.CharField(default="Africa/Dakar", max_length=64)),
                ("emergency_contact", models.CharField(blank=True, max_length=255)),
                ("bank_account", models.CharField(blank=True, max_length=64)),
                ("failed_login_count", models.PositiveIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "last_password_change",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_2fa_enabled", models.BooleanField(default=False)),
                ("totp_secret", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "utilisateur",
                "ordering": ["email"],
            },
            managers=[
                ("objects", apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_tried", models.EmailField(max_length=254)),
                ("successful", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PasswordPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_length", models.PositiveIntegerField(default=10)),
                ("require_uppercase", models.BooleanField(default=True)),
                ("require_lowercase", models.BooleanField(default=True)),
                ("require_digit", models.BooleanField(default=True)),
                ("require_symbol", models.BooleanField(default=False)),
                (
                    "expiry_days",
                    models.PositiveIntegerField(
                        default=0, help_text="0 = pas d'expiration."
                    ),
                ),
                ("max_failed_attempts", models.PositiveIntegerField(default=5)),
                ("lockout_minutes", models.PositiveIntegerField(default=15)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "politique de mot de passe",
                "verbose_name_plural": "politique de mot de passe",
            },
        ),
    ]
