# Generated by Django 5.2.17 on 2026-08-29 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("permissions", "0003_phase2_catalog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=60, unique=True)),
                ("label", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "circuit de validation",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="ValidationStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("label", models.CharField(max_length=150)),
                (
                    "approver_type",
                    models.CharField(
                        choices=[
                            ("manager", "Responsable hiérarchique du demandeur"),
                            ("role", "Titulaire d'un rôle"),
                            ("user", "Personne désignée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("skip_if_unresolved", models.BooleanField(default=True)),
                (
                    "approver_role",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="permissions.role",
                    ),
                ),
                (
                    "approver_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="validation.validationflow",
                    ),
                ),
            ],
            options={
                "ordering": ["flow", "order"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En validation"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("cancelled", "Annulé"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subject_user",
                    models.ForeignKey(
                        help_text="Personne concernée (sert à résoudre le « manager », etc.).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approval_processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processes",
                        to="validation.validationflow",
                    ),
                ),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validation.validationstep",
                    ),
                ),
            ],
            options={
                "verbose_name": "processus de validation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("returned", "Renvoyé pour correction"),
                        ],
                        max_length=16,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="validation.approvalprocess",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="validation.validationstep",
                    ),
                ),
            ],
            options={
                "ordering": ["decided_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="validationstep",
            constraint=models.UniqueConstraint(
                fields=("flow", "order"), name="uniq_flow_step_order"
            ),
        ),
        migrations.AddIndex(
            model_name="approvalprocess",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="validation__content_809a96_idx",
            ),
        ),
    ]
