# Generated by Django 5.2.17 on 2026-08-30 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("all_day", models.BooleanField(default=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("personal", "Personnel"),
                            ("task", "Tâche"),
                            ("meeting", "Réunion"),
                            ("leave", "Congé"),
                            ("reminder", "Rappel"),
                        ],
                        default="personal",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Privé"),
                            ("busy", "Occupé (détails masqués)"),
                            ("shared", "Partagé"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=7)),
                ("recurrence_rule", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "évènement d'agenda",
                "ordering": ["start"],
            },
        ),
        migrations.CreateModel(
            name="EventAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("needs_action", "À confirmer"),
                            ("accepted", "Accepté"),
                            ("declined", "Refusé"),
                            ("tentative", "Peut-être"),
                        ],
                        default="needs_action",
                        max_length=16,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_attendees",
                        to="agenda.calendarevent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="attendees",
            field=models.ManyToManyField(
                related_name="invited_events",
                through="agenda.EventAttendee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="EventReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes_before", models.PositiveIntegerField(default=15)),
                (
                    "channel",
                    models.CharField(
                        choices=[("notification", "Notification"), ("email", "E-mail")],
                        default="notification",
                        max_length=16,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="agenda.calendarevent",
                    ),
                ),
            ],
            options={
                "ordering": ["minutes_before"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventattendee",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="uniq_event_attendee"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["owner", "start"], name="agenda_cale_owner_i_17f82b_idx"
            ),
        ),
    ]
