# Generated by Django 5.2.17 on 2026-08-29 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="Identité figée de l'auteur (survit à la suppression du compte).",
                        max_length=255,
                    ),
                ),
                ("actor_is_admin", models.BooleanField(default=False)),
                ("module", models.CharField(db_index=True, max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Modification"),
                            ("delete", "Suppression"),
                            ("send", "Envoi"),
                            ("validate", "Validation"),
                            ("permission_change", "Changement de permission"),
                            ("login", "Connexion"),
                            ("logout", "Déconnexion"),
                            ("login_failed", "Échec de connexion"),
                            ("export", "Export"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("critical", "Critique"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=16,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=120)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("target_repr", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("message", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée du journal d'audit",
                "verbose_name_plural": "journal d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["module", "action"],
                        name="audit_audit_module_32c869_idx",
                    ),
                    models.Index(
                        fields=["actor", "timestamp"],
                        name="audit_audit_actor_i_447825_idx",
                    ),
                ],
            },
        ),
    ]
