# Generated by Django 5.2.17 on 2026-09-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='confidential',
            field=models.BooleanField(default=False, help_text='Entrée sensible : visible uniquement par le Super Administrateur.'),
        ),
    ]
