# Generated by Django 5.2.17 on 2026-08-29 19:29

import apps.correspondence.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Mots-clés séparés par des virgules — classement automatique.",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie de courrier",
                "verbose_name_plural": "catégories de courrier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Arrivée"), ("outgoing", "Départ")],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "correspondent",
                    models.CharField(
                        help_text="Expéditeur (arrivée) ou destinataire (départ) externe.",
                        max_length=200,
                    ),
                ),
                (
                    "mail_date",
                    models.DateField(help_text="Date figurant sur le courrier."),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "confidentiality",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("restricted", "Restreint"),
                            ("confidential", "Confidentiel"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Reçu"),
                            ("assigned", "Affecté"),
                            ("in_progress", "En traitement"),
                            ("processed", "Traité"),
                            ("archived", "Archivé"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Échéance de traitement (rappel automatique).",
                        null=True,
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_mails",
                        to="organization.department",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_mails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="correspondence.mailcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "courrier",
                "ordering": ["-registered_at"],
            },
        ),
        migrations.CreateModel(
            name="MailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.correspondence.models.mail_attachment_path
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=150)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="correspondence.mail",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("registered", "Enregistré"),
                            ("viewed", "Consulté"),
                            ("assigned", "Affecté"),
                            ("transferred", "Transféré"),
                            ("status_change", "Changement de statut"),
                            ("acknowledged", "Accusé de réception"),
                            ("commented", "Commentaire"),
                        ],
                        max_length=20,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="correspondence.mail",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="correspondence.mailcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "modèle de courrier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NumberingScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("department", "Par département"),
                        ],
                        default="global",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("incoming", "Arrivée"), ("outgoing", "Départ")],
                        max_length=10,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("counter", models.PositiveIntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MailAcknowledgement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acknowledgements",
                        to="correspondence.mail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mail", "user"), name="uniq_mail_ack"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="mail",
            index=models.Index(
                fields=["direction", "status"], name="corresponde_directi_bfaf5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mail",
            index=models.Index(
                fields=["reference"], name="corresponde_referen_b597e5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="numberingscheme",
            constraint=models.UniqueConstraint(
                fields=("scope", "department", "direction", "year"),
                name="uniq_numbering_scheme",
            ),
        ),
    ]
