# Generated by Django 5.2.17 on 2026-08-29 19:29

import apps.hr.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                (
                    "annual_quota_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("paid", models.BooleanField(default=True)),
                ("requires_certificate", models.BooleanField(default=False)),
                ("color", models.CharField(default="#D2812E", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "type de congé",
                "ordering": ["label"],
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("label", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "jour férié",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("matricule", models.CharField(max_length=30, unique=True)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("hire_date", models.DateField(blank=True, null=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("internship", "Stage"),
                            ("service", "Prestation de service"),
                            ("volunteer", "Volontariat"),
                        ],
                        default="cdi",
                        max_length=20,
                    ),
                ),
                (
                    "hr_status",
                    models.CharField(
                        choices=[
                            ("onboarding", "Intégration"),
                            ("active", "En poste"),
                            ("on_leave", "En congé"),
                            ("probation", "Période d'essai"),
                            ("left", "Parti"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("probation_end", models.DateField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("national_id", models.CharField(blank=True, max_length=50)),
                ("social_security_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "employé",
                "ordering": ["matricule"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("internship", "Stage"),
                            ("service", "Prestation de service"),
                            ("volunteer", "Volontariat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "gross_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, upload_to=apps.hr.models.contract_document_path
                    ),
                ),
                (
                    "renewal_notice_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Délai d'alerte avant l'échéance."
                    ),
                ),
                ("expiry_alert_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrat",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CareerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("promotion", "Promotion"),
                            ("training", "Formation"),
                            ("warning", "Avertissement"),
                            ("role_change", "Changement de poste"),
                            ("transfer", "Mutation"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_events",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "évènement de carrière",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("id", "Pièce d'identité"),
                            ("diploma", "Diplôme"),
                            ("certificate", "Attestation"),
                            ("contract", "Contrat"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                (
                    "file",
                    models.FileField(upload_to=apps.hr.models.employee_document_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hr.employee",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("medical_visit", "Visite médicale"),
                            ("certification", "Habilitation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=150)),
                ("date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("renewal_notice_days", models.PositiveIntegerField(default=30)),
                ("expiry_alert_sent_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "suivi médical / habilitation",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("half_day_start", models.BooleanField(default=False)),
                ("half_day_end", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, upload_to=apps.hr.models.leave_attachment_path
                    ),
                ),
                (
                    "working_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("in_review", "En validation"),
                            ("approved", "Approuvé"),
                            ("rejected", "Rejeté"),
                            ("cancelled", "Annulé"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hr.leavetype"
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de congé",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "entitled_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "carried_over_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "taken_days",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hr.leavetype"
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "leave_type", "year"),
                        name="uniq_leave_balance",
                    )
                ],
            },
        ),
    ]
