# Generated by Django 5.2.17 on 2026-08-30 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "room_slug",
                    models.CharField(editable=False, max_length=80, unique=True),
                ),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("invited", "Sur invitation"),
                            ("open", "Ouverte à tous"),
                        ],
                        default="invited",
                        max_length=16,
                    ),
                ),
                (
                    "lobby",
                    models.BooleanField(
                        default=False,
                        help_text="Salle d'attente avec validation d'entrée.",
                    ),
                ),
                ("recurrence_rule", models.CharField(blank=True, max_length=255)),
                ("agenda", models.TextField(blank=True, help_text="Ordre du jour.")),
                ("minutes", models.TextField(blank=True, help_text="Compte-rendu.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planifiée"),
                            ("ongoing", "En cours"),
                            ("ended", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="scheduled",
                        max_length=16,
                    ),
                ),
                ("reminder_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "minutes_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings_organized",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recording_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "réunion",
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="MeetingParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("needs_action", "À confirmer"),
                            ("accepted", "Accepté"),
                            ("declined", "Refusé"),
                            ("tentative", "Peut-être"),
                        ],
                        default="needs_action",
                        max_length=16,
                    ),
                ),
                ("is_organizer", models.BooleanField(default=False)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_participants",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="meeting",
            name="participants",
            field=models.ManyToManyField(
                related_name="meetings",
                through="meetings.MeetingParticipant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MeetingPoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polls",
                        to="meetings.meeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingPollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="meetings.meetingpoll",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeetingPollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="meetings.meetingpolloption",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="meetingparticipant",
            constraint=models.UniqueConstraint(
                fields=("meeting", "user"), name="uniq_meeting_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="meetingpollvote",
            constraint=models.UniqueConstraint(
                fields=("option", "user"), name="uniq_poll_option_vote"
            ),
        ),
    ]
