# Generated by Django 5.2.17 on 2026-08-31 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('kind', models.CharField(choices=[('absent', 'Absent'), ('remote', 'Télétravail'), ('morning', 'Indisponible le matin'), ('afternoon', "Indisponible l'après-midi"), ('mission', 'En mission / terrain')], default='absent', max_length=20)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'disponibilité',
                'verbose_name_plural': 'disponibilités',
                'ordering': ['-start_date'],
            },
        ),
    ]
