# Generated by Django 5.2.17 on 2026-10-04 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('component', models.CharField(blank=True, help_text='Service concerné (ex. Postgres, Directus, API, messagerie).', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Mineur'), ('medium', 'Modéré'), ('high', 'Majeur'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('investigating', "En cours d'investigation"), ('resolved', 'Résolu'), ('closed', 'Clôturé')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_assigned', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'incident technique',
                'verbose_name_plural': 'incidents techniques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='system_inci_status_49cab8_idx')],
            },
        ),
    ]
